node {
   def commit_id
   stage('Preparation') {
     checkout scm //Cloning the whole Git Repo so we can star working with it 
     sh "git rev-parse --short HEAD > .git/commit-id"    //sh=shell command. We store commit id with this command                    
     commit_id = readFile('.git/commit-id').trim() //Set commit id variable to the commit id we just created
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') { //Set NodeJs Installation Name.
       sh 'npm install --only=dev' //Install npm development packages.
       sh 'npm test' //Start Npm Test. Its going to execute test.js
     }
   }
   stage('docker build/push') { 
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') { //Set Registry
       def app = docker.build("munmo/docker-nodejs-demo:${commit_id}", '.').push() //Do the pushing in the specifed repo with the created commit id.
     }
   }
}
